// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDub0BXlChb-Z702hvDdOm2mCIZDLdPZWE',
    appId: '1:566789646894:web:57c1de7a61c4da2e2a4dbf',
    messagingSenderId: '566789646894',
    projectId: 'cash2-44e50',
    authDomain: 'cash2-44e50.firebaseapp.com',
    storageBucket: 'cash2-44e50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMaqyyRzj78acaFzBdhdEgtSipM7m3rk',
    appId: '1:566789646894:android:a31d0724dfbba1b42a4dbf',
    messagingSenderId: '566789646894',
    projectId: 'cash2-44e50',
    storageBucket: 'cash2-44e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKjnFyIlXvv5a3hJ9ygqd-KsYIhpBZZlQ',
    appId: '1:566789646894:ios:0e8e0bdc4f0bdd7d2a4dbf',
    messagingSenderId: '566789646894',
    projectId: 'cash2-44e50',
    storageBucket: 'cash2-44e50.firebasestorage.app',
    iosBundleId: 'com.example.cashCollector02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKjnFyIlXvv5a3hJ9ygqd-KsYIhpBZZlQ',
    appId: '1:566789646894:ios:0e8e0bdc4f0bdd7d2a4dbf',
    messagingSenderId: '566789646894',
    projectId: 'cash2-44e50',
    storageBucket: 'cash2-44e50.firebasestorage.app',
    iosBundleId: 'com.example.cashCollector02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDub0BXlChb-Z702hvDdOm2mCIZDLdPZWE',
    appId: '1:566789646894:web:41e725dfbbc3fd752a4dbf',
    messagingSenderId: '566789646894',
    projectId: 'cash2-44e50',
    authDomain: 'cash2-44e50.firebaseapp.com',
    storageBucket: 'cash2-44e50.firebasestorage.app',
  );
}
